language: node_js
node_js:
  - "14"

# S: Build Lifecycle
install:
  - npm install
  #before_script:
# - npm install -g gulp

script:
  - hexo g

after_script:
 - cd ./public
 - git init
 - git config user.name "xuegangliu"
 - git config user.email "1453860636@qq.com"
 - git add .
 - git commit -m "Update docs"
 - git push origin template:gh-pages
#  - git push --force --quiet "https://${token}@https://github.com/xuegangliu/blog.git" template:gh-pages
## E: Build LifeCycle

branches:
  only:
    - template

#env:
#  global:
#    - GH_REF_ADDRESS: https://github.com/xuegangliu/blog.git

# GitHub Pages 部署
deploy:
  skip_cleanup: true
  provider: pages
  cleanup: true
  # 在项目仪表盘的 Settings -> Environment Variables 中配置
  token: $token
  # 将 build 目录下的内容推送到默认的 gh-pages 分支上，并不会连带 build 目录一起
  local_dir: public
  keep_history: true
  #fqdn: $CUSTOM_DOMAIN
  name: xuegangliu
  email: 1453860636@qq.com
  on:
    branch: template
